language: node_js
node_js:
  - "node"
#   - "8"
#  - "6"


env:
  - COUCHDB_VERSION=2.3.1 COUCHDB_USER=james COUCHDB_PASSWORD=grobblefruit


addons:
  code_climate:
    # repo_token: d7647668fe8eb1da34633b937e6e168652d7d1ad1d727601981eea12bf4edb1d

services:
  - docker

before_install:
  - docker pull couchdb:$COUCHDB_VERSION
  - docker run -d  -e COUCHDB_USER=$COUCHDB_USER  -e COUCHDB_PASSWORD=$COUCHDB_PASSWORD -p 5984:5984 couchdb:$COUCHDB_VERSION


before_script:
  # Make sure CouchDB is up
  - while [ $? -ne 0 ]; do sleep 1 && curl -v http://localhost:5984; done
  - echo "{\"couchdb\":{\"host\":\"127.0.0.1\",\"port\":5984,\"db\":\"a_teststatedb\",\"auth\":{\"username\":\"${COUCHDB_USER}\",\"password\":\"${COUCHDB_PASSWORD}\"}}}" > test.config.json && chmod 0600 test.config.json

notifications:
  email:
    on_success: change
    on_failure: change

# after_success:
  # - npm install codeclimate-test-reporter
  # - ./node_modules/.bin/tap --coverage-report=text-lcov | ./node_modules/.bin/codeclimate-test-reporter
